name: Build Docs
run-name: ${{ github.actor }} is building docs
on: [push]
jobs:
  Build-Docs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install dependencies
        run: |
          python3 -m pip install sphinx sphinx-rtd-theme sphinxcontrib-jquery
      - name: Install atmst python module
        run: |
          python3 -m pip install .
      - name: Build the docs
        run: |
          cd ./docs/
          sphinx-apidoc -f -o _apidocs/ ../src/atmst
          make html
          touch _build/html/.nojekyll
      - name: Archive generated docs
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/_build/html/
      - name: Push docs to gh pages
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: docs/_build/html/
          destination-github-username: DavidBuchanan314
          destination-repository-name: davidbuchanan314.github.io
          target-directory: atmst/
          user-email: d@vidbuchanan.co.uk
          target-branch: master
