name: Run tests
run-name: ${{ github.actor }} is running tests
on: push
jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.11', '3.12', '3.13' ]
    name: Python ${{ matrix.python-version }} tests
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install atmst python module
        run: |
          python3 -m pip install -v .
      - name: Run the tests
        run: |
          python3 -m unittest -v
